"""
Summary Reporter — Generates Markdown summary.md and JSON execution-results.json.
"""

import json
import os
import sys
import argparse
from datetime import datetime


def generate_summary(results: dict, output_path: str, build: str = 'N/A',
                     commit: str = 'N/A', branch: str = 'N/A'):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    metrics = results.get('metrics', {})
    tests   = results.get('test_cases', [])

    passed  = metrics.get('passed',  sum(1 for t in tests if t.get('status','').upper() == 'PASSED'))
    failed  = metrics.get('failed',  sum(1 for t in tests if t.get('status','').upper() == 'FAILED'))
    skipped = metrics.get('skipped', sum(1 for t in tests if t.get('status','').upper() == 'SKIPPED'))
    total   = metrics.get('total', len(tests))
    pass_rate = (passed / total * 100) if total > 0 else 0
    status_icon = '✅' if pass_rate >= 95 else '⚠️' if pass_rate >= 70 else '❌'

    passed_tests  = [t for t in tests if t.get('status','').upper() == 'PASSED']
    failed_tests  = [t for t in tests if t.get('status','').upper() == 'FAILED']
    skipped_tests = [t for t in tests if t.get('status','').upper() == 'SKIPPED']

    passed_list  = '\n'.join(f'  ✓ {t["id"]} — {t["name"]}' for t in passed_tests[:30])
    failed_list  = '\n'.join(
        f'  ✗ {t["id"]} — {t["name"]}\n    Reason: {t.get("failure_reason","Unknown")}'
        for t in failed_tests[:20]
    )
    skipped_list = '\n'.join(
        f'  - {t["id"]} — Reason: {t.get("failure_reason","Feature disabled")}'
        for t in skipped_tests[:10]
    )

    md = f"""# {status_icon} Android Appium E2E Execution Summary

| Field | Value |
|-------|-------|
| **Build Number** | #{build} |
| **Execution Date** | {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} |
| **Git Commit** | `{commit[:12]}` |
| **Branch** | `{branch}` |
| **APK Version** | {metrics.get('app_version','1.0.0')} |
| **Device** | {metrics.get('device','E2E_Emulator')} |
| **Android Version** | {metrics.get('android_version','14')} |

---

## 📊 Execution Metrics

| Metric | Count | Percentage |
|--------|-------|------------|
| **Total Test Cases** | {total} | 100% |
| ✅ **Passed** | {passed} | {pass_rate:.1f}% |
| ❌ **Failed** | {failed} | {(failed/total*100) if total > 0 else 0:.1f}% |
| ⏭️ **Skipped** | {skipped} | {(skipped/total*100) if total > 0 else 0:.1f}% |
| ⏱️ **Duration** | {metrics.get('duration','N/A')} | — |

**Pass Rate: {pass_rate:.1f}%** {status_icon}

---

## ✅ Passed Tests (showing first 30)

```
{passed_list if passed_list else '  No tests passed.'}
```

---

## ❌ Failed Tests

```
{failed_list if failed_list else '  No tests failed. 🎉'}
```

---

## ⏭️ Skipped Tests

```
{skipped_list if skipped_list else '  No tests skipped.'}
```

---

## 🔗 Reports

- 📄 [HTML Execution Report](../HTML/execution-report.html)
- 📊 [Excel Report](../Excel/Automation_Test_Report.xlsx)
- 📋 [JSON Results](../JSON/execution-results.json)
- 📸 Screenshots: `automation/screenshots/`
- 📋 Logs: `automation/logs/`

---
*Generated by Image Authenticity Verification App Automation Suite | Build #{build}*
"""

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(md)

    print(f"[OK] Markdown summary written: {output_path}")

    return output_path


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--input',   required=True)
    parser.add_argument('--output',  required=True)
    parser.add_argument('--build',   default='N/A')
    parser.add_argument('--commit',  default='N/A')
    parser.add_argument('--branch',  default='N/A')
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"❌ Input not found: {args.input}")
        sys.exit(1)

    with open(args.input) as f:
        results = json.load(f)

    generate_summary(results, args.output, args.build, args.commit, args.branch)
